### PR TITLE
Don't hide Cargo.lock

### PR DESCRIPTION
**Pull request by 0323pin**
And a few tweaks to README.md

Maybe add an example of `rsushrc` to make life easier for potential users?

### CODE REVIEW

**Comment by luckboy** [comment]
Why shouldn't I hide Cargo.toml?
Whether are README.md tweaks necessary?
I want release new version of this shell on Monday.

**Comment by 0323pin** [comment]
Ok, remove the changes on README.md if you want, just though the text would flow better with the changes I did.

As for Cargo.lock, we have a script that reads the file and generates a list of dependency crates. Without Cargo.lock I need to this manually. First generate the file, then use a bunch of `sed -i` to do replacements and finally a manual edit to format it. If Cargo.lock is present all these are automatically done.

**Comment by luckboy** [comment]
When I clone my repository and build this shell without Cargo.lock, my shell is built.

**Comment by 0323pin** [comment]
True but, I'm creating a NetBSD package for it. Without Cargo.lock, I need to fetch the sources and locally run `cargo generate-lockfile` and then through several manual steps convert it into the following,

```
# $NetBSD$

CARGO_CRATE_DEPENDS+=	bitflags-1.3.2
CARGO_CRATE_DEPENDS+=	cc-1.0.73
CARGO_CRATE_DEPENDS+=	cfg-if-1.0.0
CARGO_CRATE_DEPENDS+=	clipboard-win-4.4.2
CARGO_CRATE_DEPENDS+=	dirs-next-2.0.0
CARGO_CRATE_DEPENDS+=	dirs-sys-next-0.1.2
CARGO_CRATE_DEPENDS+=	endian-type-0.1.2
CARGO_CRATE_DEPENDS+=	errno-0.2.8
CARGO_CRATE_DEPENDS+=	errno-dragonfly-0.1.2
CARGO_CRATE_DEPENDS+=	error-code-2.3.1
CARGO_CRATE_DEPENDS+=	fastrand-1.8.0
CARGO_CRATE_DEPENDS+=	fd-lock-3.0.6
CARGO_CRATE_DEPENDS+=	fnmatch-sys-1.0.0
CARGO_CRATE_DEPENDS+=	fnv-1.0.7
CARGO_CRATE_DEPENDS+=	fs_extra-1.2.0
CARGO_CRATE_DEPENDS+=	getopt-1.1.3
CARGO_CRATE_DEPENDS+=	getrandom-0.2.7
CARGO_CRATE_DEPENDS+=	instant-0.1.12
CARGO_CRATE_DEPENDS+=	io-lifetimes-0.7.3
CARGO_CRATE_DEPENDS+=	libc-0.2.132
CARGO_CRATE_DEPENDS+=	linux-raw-sys-0.0.46
CARGO_CRATE_DEPENDS+=	log-0.4.17
CARGO_CRATE_DEPENDS+=	memchr-2.5.0
CARGO_CRATE_DEPENDS+=	nibble_vec-0.1.0
CARGO_CRATE_DEPENDS+=	nix-0.24.2
CARGO_CRATE_DEPENDS+=	proc-macro2-1.0.43
CARGO_CRATE_DEPENDS+=	quick-error-1.2.3
CARGO_CRATE_DEPENDS+=	quote-1.0.21
CARGO_CRATE_DEPENDS+=	radix_trie-0.2.1
CARGO_CRATE_DEPENDS+=	redox_syscall-0.2.16
CARGO_CRATE_DEPENDS+=	redox_users-0.4.3
CARGO_CRATE_DEPENDS+=	remove_dir_all-0.5.3
CARGO_CRATE_DEPENDS+=	rustix-0.35.9
CARGO_CRATE_DEPENDS+=	rusty-forkfork-0.4.0
CARGO_CRATE_DEPENDS+=	rustyline-10.0.0
CARGO_CRATE_DEPENDS+=	scopeguard-1.1.0
CARGO_CRATE_DEPENDS+=	sealed_test-1.0.0
CARGO_CRATE_DEPENDS+=	sealed_test_derive-1.0.0
CARGO_CRATE_DEPENDS+=	smallvec-1.9.0
CARGO_CRATE_DEPENDS+=	str-buf-1.0.6
CARGO_CRATE_DEPENDS+=	syn-1.0.99
CARGO_CRATE_DEPENDS+=	tempfile-3.3.0
CARGO_CRATE_DEPENDS+=	thiserror-1.0.35
CARGO_CRATE_DEPENDS+=	thiserror-impl-1.0.35
CARGO_CRATE_DEPENDS+=	unicode-ident-1.0.4
CARGO_CRATE_DEPENDS+=	unicode-segmentation-1.10.0
CARGO_CRATE_DEPENDS+=	unicode-width-0.1.10
CARGO_CRATE_DEPENDS+=	utf8parse-0.2.0
CARGO_CRATE_DEPENDS+=	wait-timeout-0.2.0
CARGO_CRATE_DEPENDS+=	wasi-0.11.0+wasi-snapshot-preview1
CARGO_CRATE_DEPENDS+=	winapi-0.3.9
CARGO_CRATE_DEPENDS+=	winapi-i686-pc-windows-gnu-0.4.0
CARGO_CRATE_DEPENDS+=	winapi-x86_64-pc-windows-gnu-0.4.0
CARGO_CRATE_DEPENDS+=	windows-sys-0.36.1
CARGO_CRATE_DEPENDS+=	windows_aarch64_msvc-0.36.1
CARGO_CRATE_DEPENDS+=	windows_i686_gnu-0.36.1
CARGO_CRATE_DEPENDS+=	windows_i686_msvc-0.36.1
CARGO_CRATE_DEPENDS+=	windows_x86_64_gnu-0.36.1
CARGO_CRATE_DEPENDS+=	windows_x86_64_msvc-0.36.1
```

If Cargo.lock is there, this file is autogenerated. So basically, a lot of work for me when it isn't.

**Comment by luckboy** [comment]
Can't you automate this conversion process?

**Comment by luckboy** [comment]
I don't want have problems with versions of Cargo.lock files.

**Comment by 0323pin** [comment]
The process is already automated, it reads `Cargo.lock`.

> I don't want have problems with versions of Cargo.lock files.

What do you mean? You can automate it's generation.

This is unfortunate, I don't want to maintain a package requiring this amount of hand-holding.
Let me know if you change your mind, the package is ready to be merged.

**Comment by luckboy** [comment]
> What do you mean? You can automate it's generation.

Many people can have different versions of Cargo.lock files in their local repos.
I want have own version of Cargo.lock in my local repo.

**Pull request closed without merging**
